name: howie yagaloo photography
favicon: null
layout_spectrum: 0.51694
typography_spectrum: 0.7098997
title: This is Howie Yagaloo Photography.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FDFCFD'
    - '#020102'
    - '#C7886D'
    - '#9A5C41'
    - '#8891B4'
  brandStrength: 0
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
