name: howie yagaloo photography
favicon: null
layout_spectrum: 0.8069
typography_spectrum: 0.31501
title: Willkommen auf der TheGrid Testseite von Howie Yagaloo Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9481115762609988
  lightness: 0.9901801899541169
  saturation: 0.7017928829882294
  rhythmicContrast: 0.9427130979020149
purpose: []
