name: howie yagaloo photography
favicon: null
layout_spectrum: 0.24197
typography_spectrum: 0.5921053
title: This is Howie Yagaloo Photography.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
